[package]
name = "dev_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { version = "0.25.0", features = ["serde", "persistence"] }
dirs = "5.0.1"
env_logger = "0.11.0"
once_cell = "1.19.0"
anyhow = "1"
nom = "7.1.3"

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
